[package]
name = "convert-screenshot"
version = "1.0.0"
edition = "2024"
description = "Convert game screenshot"
build = "build.rs"

[[bin]]
name = "cs"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = "z"
strip = true

[dependencies]
clap = { version = "4.5", features = ["derive", "env", "string", "unicode", "wrap_help"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
