[workspace]
members = [
  "cli",
  "common",
  "gui",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.87"
version = "1.2.3"

[workspace.dependencies]
winresource = "^0.1"

[profile.release]
lto = true # "thin"
opt-level = "s"
strip = true
