# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:

tasks:
  default:
    cmds:
      - task: build:windows
  build:windows:
    cmds:
      - cargo build --color=always --profile release
      - coreutils cp --remove-destination ./target/release/cs.exe .
