[package]
name = "common"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true, optional = true }
serde.workspace = true

[features]
cli = [ "clap" ]
default = []
